baseURL = "https://hugo-gutierrez-pe.github.io/"
languageCode = "es-PE"
title = "Hugo Gutierrez"

enableRobotsTXT = true
enableGitInfo = false

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML"]
  section = ["HTML", "RSS"]

[minify]
  disableHTML = true
