baseURL = "https://hugo-gutierrez-pe.github.io/"
languageCode = "es-PE"
title = "Hugo Gutierrez"

enableRobotsTXT = true
enableGitInfo = false

[pagination]
  pagerSize = 10

disableKinds = ["home"]

[outputs]
  section = ["HTML", "RSS"]
